AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  cognitoauth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python3.6
      Policies: 
        - AmazonCognitoPowerUser
        - AmazonDynamoDBFullAccess
      CodeUri: s3://marek-serverless/serverless-cognito.zip
      Description: ''
      MemorySize: 128
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          userpoolid: !Ref cognitopool
          clientid: !Ref cognitoclient

  cookies:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "user"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "user"
          KeyType: "HASH"        

      BillingMode: PAY_PER_REQUEST

  cognitopool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        UnusedAccountValidityDays: 1
      AliasAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  cognitoclient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId:
        Ref: cognitopool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

Outputs:
  WebInterface:
    Value: { "Fn::Sub" : "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"}